- name: Install basic packages
  hosts: virtualmachines
  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      ansible.builtin.apt:
        update_cache: yes
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
    - name: install vim
      ansible.builtin.apt:
        name: vim
        state: present
    - name: install zsh
      ansible.builtin.apt:
        name: zsh
        state: present
    - name: install lf
      ansible.builtin.apt:
        name: lf
        state: present
    - name: install zoxide
      ansible.builtin.apt:
        name: zoxide
        state: present
    - name: install tmux
      ansible.builtin.apt:
        name: tmux
        state: present
    - name: install dialog
      ansible.builtin.apt:
        name: dialog
        state: present
    - name: install fzf
      ansible.builtin.apt:
        name: fzf
        state: present
    - name: install htop
      ansible.builtin.apt:
        name: htop
        state: present
    - name: install ncdu
      ansible.builtin.apt:
        name: ncdu
        state: present
    - name: install peco
      ansible.builtin.apt:
        name: peco
        state: present
    - name: install net-tools
      ansible.builtin.apt:
        name: net-tools
        state: present
    - name: install tree
      ansible.builtin.apt:
        name: tree
        state: present
    - name: install curl
      ansible.builtin.apt:
        name: curl
        state: present
    - name: install wget
      ansible.builtin.apt:
        name: wget
        state: present
    - name: install trash-cli
      ansible.builtin.apt:
        name: trash-cli
        state: present
    - name: install speedtest-cli
      ansible.builtin.apt:
        name: speedtest-cli
        state: present
    - name: install postfix
      ansible.builtin.apt:
        name: postfix
        state: present
    - name: install libsasl2-modules
      ansible.builtin.apt:
        name: libsasl2-modules
        state: present
    - name: install unattended-upgrades
      ansible.builtin.apt:
        name: unattended-upgrades
        state: present
    - name: install apt-listchanges
      ansible.builtin.apt:
        name: apt-listchanges
        state: present
    - name: install neofetch
      ansible.builtin.apt:
        name: neofetch
        state: present
    - name: install fail2ban
      ansible.builtin.apt:
        name: fail2ban
        state: present
    - name: install molly-guard
      ansible.builtin.apt:
        name: molly-guard
        state: present
    - name: install git
      ansible.builtin.apt:
        name: git
        state: present
    - name: install zip
      ansible.builtin.apt:
        name: zip
        state: present
    - name: install unzip
      ansible.builtin.apt:
        name: unzip
        state: present
    - name: install tar
      ansible.builtin.apt:
        name: tar
        state: present
    - name: install less
      ansible.builtin.apt:
        name: less
        state: present
    - name: install rsync
      ansible.builtin.apt:
        name: rsync
        state: present
    - name: install tshark
      ansible.builtin.apt:
        name: tshark
        state: present
    - name: install bpytop
      ansible.builtin.apt:
        name: bpytop
        state: present
    - name: install fdupes
      ansible.builtin.apt:
        name: fdupes
        state: present
    - name: install iftop
      ansible.builtin.apt:
        name: iftop
        state: present
    - name: install iotop
      ansible.builtin.apt:
        name: iotop
        state: present
    - name: install needrestart
      ansible.builtin.apt:
        name: needrestart
        state: present
    - name: install miller
      ansible.builtin.apt:
        name: miller
        state: present
    - name: install lsof
      ansible.builtin.apt:
        name: lsof
        state: present
    - name: install ltrace
      ansible.builtin.apt:
        name: ltrace
        state: present
    - name: install strace
      ansible.builtin.apt:
        name: strace
        state: present
    - name: install netcat
      ansible.builtin.apt:
        name: netcat
        state: present
    - name: install mailutils
      ansible.builtin.apt:
        name: mailutils
        state: present
    - name: install mmv
      ansible.builtin.apt:
        name: mmv
        state: present
    - name: install rlwrap
      ansible.builtin.apt:
        name: rlwrap
        state: present
    - name: install needrestart
      ansible.builtin.apt:
        name: needrestart
        state: present
    - name: install psmisc
      ansible.builtin.apt:
        name: psmisc
        state: present
    - name: install atool
      ansible.builtin.apt:
        name: atool
        state: present
    - name: install etckeeper
      ansible.builtin.apt:
        name: etckeeper
        state: present

- name: Install proxmox packages
  hosts: virtualmachines
  tasks:
    - name: Set a hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"
        use: systemd
    - name: Add IP address of all hosts to all hosts
      lineinfile:
        dest: /etc/hosts
        #regexp: ".*{{ item }}$"
        line: "{{ ansible_host }} {{ hostname }} {{ domainname }} {{hostname}}.{{ domainname }}"
        state: present
      #with_items: "{{ groups.all }}"
    - name: Add proxmox repo keys
      ansible.builtin.get_url:
        url: https://enterprise.proxmox.com/debian/proxmox-release-bullseye.gpg
        dest: /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg
    - name: Add proxmox repo into source liste
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] http://download.proxmox.com/debian/pve bullseye pve-no-subscription
        state: present
        filename: pve-install-repo.list
    - name: install proxmox pve-kernel-5.19
      ansible.builtin.apt:
        name: pve-kernel-5.19
        state: present
    - name: remove default linux kernel
      ansible.builtin.apt:
        name: linux-image-amd64
        state: absent
    - name: remove default linux kernel 5.10*
      ansible.builtin.apt:
        name: linux-image-5.10*
        state: absent
    - name: update-grub
      shell: update-grub
    - name:
      ansible.builtin.reboot:
    - name: Install ifupdown2
      shell: tmux new-session -d "apt install -y ifupdown2; apt purge -y ifupdown; systemctl unmask networking; systemctl restart networking; apt install -y --reinstall ifupdown2; reboot"
    - name: Pause for wait network after ifupdown2 install
      ansible.builtin.pause:
        minutes: 3
    - name: install open-iscsi
      ansible.builtin.apt:
        name: open-iscsi
        state: present
    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot:
    - name: install proxmox-ve
      ansible.builtin.apt:
        name: proxmox-ve
        state: present
    - name: remove os-prober
      ansible.builtin.apt:
        name: os-prober
        state: absent
